---
title: "Class14"
author: "Yuansheng Zhou"
date: "5/17/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
counts <- read.csv("data/airway_scaledcounts.csv", stringsAsFactors = FALSE)
metadata <-  read.csv("data/airway_metadata.csv", stringsAsFactors = FALSE)
View(metadata)
control <- metadata[metadata[,"dex"]=="control",]
control.mean <- rowSums( counts[ ,control$id] )/length(control$id) 
names(control.mean) <- counts$ensgene
```
```{r}
treated <- metadata[metadata[,"dex"]=="treated",]
treated.mean <- rowSums( counts[ ,treated$id] )/length(treated$id) 
names(treated.mean) <- treated$ensgene
```

```{r}
meancounts <- data.frame(RowNames = counts$ensgene, control.mean, treated.mean)
meancounts$log2fc <- log2(meancounts[,"treated.mean"]/meancounts[,"control.mean"])


```
```{r}
zero.vals <- which(meancounts[,1:2]==0, arr.ind=TRUE)
to.rm <- unique(zero.vals[,1])
mycounts <- meancounts[-to.rm,]
```
```{r}
up.ind <- mycounts$log2fc > 2
down.ind <- mycounts$log2fc < (-2)
```

```{r}
anno <- read.csv("data/annotables_grch38.csv")
head(anno)
```
```{r}
source("http://bioconductor.org/biocLite.R")
biocLite()
mycounts_anno <- merge(mycounts,anno, by.x = "RowNames", by.y = "ensgene")
```
```{r}
#biocLite("AnnotationDbi")
library("AnnotationDbi")
#biocLite("org.Hs.eg.db")
library("org.Hs.eg.db")
```
```{r}
#require("org.Hs.eg.db")
#keys <- head( keys(org.Hs.eg) )
mycounts$symbol <- mapIds(org.Hs.eg.db,
                     keys=row.names(mycounts),
                     column="ENTREZID",
                     keytype="ENSEMBL",
                     multiVals="first")
```

```{r}
require(org.Hs.eg.db)
## display the columns
columns(org.Hs.eg.db)
## get the 1st 6 possible keys
keys <- head( keys(org.Hs.eg.db) )
keys
```

```{r}
library(DESeq2)
citation("DESeq2")
```
```{r}
dds <- DESeqDataSetFromMatrix(countData=counts, 
                              colData=metadata, 
                              design=~dex, 
                              tidy=TRUE)
dds <- DESeq(dds)
res <- results(dds)
res05 <- results(dds, alpha=0.05)
summary(res05)
resSig05 <- subset(as.data.frame(res), padj < 0.05)
nrow(resSig05)
```
```{r}

resSig01 <- subset(as.data.frame(res), padj < 0.01)
nrow(resSig01)
resSig01$symbol <- mapIds(org.Hs.eg.db,
                     keys=row.names(resSig01),
                     column="SYMBOL",
                     keytype="ENSEMBL",
                     multiVals="first")
ord <- order( resSig01$padj )
#View(res01[ord,])
head(resSig01[ord,])
write.csv(resSig01[ord,], "signif01_results.csv")
```

```{r}
i <- grep("CRISPLD2", resSig01$symbol)
resSig01[i,]
rownames(resSig01[i,])
plotCounts(dds, gene="ENSG00000103196", intgroup="dex")
d <- plotCounts(dds, gene="ENSG00000103196", intgroup="dex", returnData=TRUE)
head(d)
boxplot(count ~ dex , data=d)
library(ggplot2)
ggplot(d, aes(dex, count)) + geom_boxplot(aes(fill=dex)) + scale_y_log10() + ggtitle("CRISPLD2")
```

```{r}
res$sig <- res$padj<0.05

# How many of each?
table(res$sig)
plotMA(res, ylim=c(-2,2))
resLFC <- lfcShrink(dds, coef=2)
plotMA(resLFC, ylim=c(-2,2))
ggplot(as.data.frame(res), aes(log2FoldChange, -1*log10(pvalue), col=sig)) + 
    geom_point() + 
    ggtitle("Volcano plot")
```


```{r}
vsdata <- vst(dds, blind=FALSE)
plotPCA(vsdata, intgroup="dex")

```

